# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    # bucket         = "terragrunt-tf-chicken-before-eggs"
    # dynamodb_table = "terragrunt_locks"
    # encrypt        = true
    # key            = "./terraform.tfstate"
    # region         = "us-east-1"
  }
}
